### ISSUE TITLE
There is no "hector_mapstitch"

### ISSUE THREAD

**Issue by LavrenovRoman** [tu-darmstadt-ros-pkg/hector_visualization#1]
Hello!
When trying to compile I see - "Could not find a package configuration file provided by "hector_mapstitch"
Problem in - hector_visualization/hector_rqt_plugins/CMakeLists.txt:5
There is no "hector_mapstitch" in packages.
Thanks.

**Comment by skohlbr** [comment]
You have to add https://github.com/tu-darmstadt-ros-pkg/mapstitch/tree/hector_mapstitch to your workspace. Alternatively, you can perform a "touch CATKIN_IGNORE" in https://github.com/tu-darmstadt-ros-pkg/hector_visualization/tree/master/hector_rqt_plugins.

**Comment by LavrenovRoman** [comment]
But "https://github.com/tu-darmstadt-ros-pkg/mapstitch/tree/hector_mapstitch" doesn't open for download. Directory "tree" is not exist in  https://github.com/tu-darmstadt-ros-pkg/mapstitch

**Comment by LavrenovRoman** [comment]
Thanks a lot!

**Comment by skohlbr** [comment]
Closing as it appears issue has been solved.
